plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.hybrid.androidhost'
    compileSdk 37

    defaultConfig {
        applicationId 'com.example.hybrid.androidhost'
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation project(':flutter')
}
